# -*- encoding: utf-8 -*-
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'request_id/version'

Gem::Specification.new do |gem|
  gem.name          = "request_id"
  gem.version       = RequestId::VERSION
  gem.authors       = ["Pawel Kondzior"]
  gem.email         = ["pawel@kondzior.com"]
  gem.description   = %q{The unique request id is either based off the X-Request-Id header in the request, which would
                        typically be generated by a firewall, load balancer, or the web server, or, if this header is
                        not available, a random uuid. If the header is accepted from the outside world, we sanitize it
                        to a max of 255 chars and alphanumeric and dashes only.}
  gem.summary       = %q{Rails 3.2 ActionDispatch::RequestId backport}
  gem.homepage      = "https://github.com/pkondzior/tagged_logging/"

  gem.files         = `git ls-files`.split($/)
  gem.executables   = gem.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
  gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})
  gem.require_paths = ["lib"]

  gem.add_dependency "rails", "~> 3.0"
end
